version: '3.9'
services:
  db:
    image: ankane/pgvector
    container_name: ecommerce_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
