version: '3.9'

services:
  ecommerce_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce_api:latest
    container_name: ecommerce_api
    ports:
      - "5001:5000"
    networks:
      - orderpage_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - EnableSwaggerInProd=true

networks:
  orderpage_network:
    external: true
