version: '3.9'

services:
  ecommerce_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce_api:latest
    container_name: ecommerce_api
    ports:
      - "5001:5000"
    networks:
      - orderpage_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=ecommerce_pg;Port=5432;Database=ecommerce;Username=postgres;Password=postgres
      - Jwt__JwtSecret=your-secret
      - Jwt__ValidIssuer=yourissuer
      - Jwt__ValidAudience=youraudience
      - EnableSwaggerInProd=true

networks:
  orderpage_network:
    external: true
